# Generated by Django 4.1.5 on 2023-01-16 12:03

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('mainapp', 'User')
    User(user_name="User 001", email="user001@email.com").save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
